# Generated by Django 4.1.5 on 2023-05-31 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=265)),
                ('email_or_contact', models.CharField(max_length=265, validators=[django.core.validators.RegexValidator(message='Please enter a valid email or contact number.', regex='^(\\d{10}|\\w+@\\w+\\.\\w{2,3})$')])),
                ('subject', models.CharField(blank=True, max_length=265)),
                ('message', models.CharField(blank=True, max_length=265)),
                ('feedback', models.CharField(blank=True, choices=[('How accurate does Predicted look to you?', 'How accurate does Predicted look to you?'), ('Probably Right', 'Probably Right'), ('High', 'High'), ('Low', 'Low')], max_length=265)),
            ],
        ),
    ]
