# Generated by Django 4.1.5 on 2023-05-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='feedback',
            field=models.CharField(blank=True, choices=[('Probably Right', 'Probably Right'), ('High', 'High'), ('Low', 'Low')], default='How accurate does Predicted Result looks to you', max_length=265),
        ),
    ]
