# Generated by Django 4.1.5 on 2023-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0006_remove_enquiry_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('Probably Right', 'Probabaly Right'), ('High', 'High'), ('Low', 'Low')], default='Probabaly Right', max_length=20)),
            ],
        ),
    ]
