# Generated by Django 4.1.5 on 2023-05-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0008_alter_feedbackmodel_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='feedback',
            field=models.CharField(choices=[('How accurate does this  look to you?', 'How accurate does this  look to you?'), ('Probably Right', 'Probabaly Right'), ('High', 'High'), ('Low', 'Low')], default='How accurate does this  look to you?', max_length=210),
        ),
    ]
