# Generated by Django 4.1.5 on 2023-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0009_alter_feedbackmodel_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='feedback',
            field=models.CharField(choices=[('Select', 'Select'), ('Probably Right', 'Probabaly Right'), ('High', 'High'), ('Low', 'Low')], default='Select', max_length=210),
        ),
    ]
