# Generated by Django 4.1.5 on 2023-05-31 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0010_alter_feedbackmodel_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedbackmodel',
        ),
    ]
